services:
  postgres:
    container_name: alert360
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=emergencia_personal"
      - "POSTGRES_PASSWORD=alert360"
      - "POSTGRES_USER=emergencia_user"
    ports:
      - "5432:5432"
    volumes:
      - ./emergencia_personal.sql:/docker-entrypoint-initdb.d/emergencia_personal.sql
